name: Search for bestdeepl

on:
  schedule:
    - cron: '0 8 * * *'  # 每天08:00运行
  workflow_dispatch:    # 允许手动启动

permissions:
  contents: write  # 赋予写入权限以便推送更改

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp aiofiles

    - name: Run script
      run: |
        python check.py

    - name: Configure Git
      run: |
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -A
        git commit -m "Update success_result.txt" || echo "No changes to commit."
        git push origin HEAD:${{ github.ref }}
